# Generated by Django 5.2.4 on 2025-08-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookOutlet', '0002_book_author_book_is_bestselling_alter_book_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-rating'], 'verbose_name': 'BookInformation'},
        ),
    ]
