# Generated by Django 5.2.5 on 2025-09-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookOutlet', '0004_alter_book_options_remove_book_is_bestselling_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('verify_email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
            ],
        ),
    ]
