# Generated by Django 5.2.5 on 2025-11-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookOutlet', '0008_book_copies_available_book_isbn_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.CharField(blank=True, help_text='Book cover image filename', max_length=100, null=True),
        ),
    ]
